apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-for-fluent-bit
  namespace: amazon-cloudwatch
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::992382478305:role/EKS-FluentBit-Role